### ISSUE TITLE
`options is not defined` error running sls dynamodb start

### ISSUE THREAD

**Issue by maikokuppe** [99xt/serverless-dynamodb-local#116]
After the merge of #114 I'm getting an error when running `sls dynamodb start`:

```
maiko@shiver:~/code/npm/backend-build-user-preferences$ SLS_DEBUG=1 sls dynamodb start
Dynamodb Local Started, Visit: http://localhost:8000/shell
 
  Reference Error ----------------------------------------
 
  options is not defined
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
ReferenceError: options is not defined
    at BbPromise.resolve.then (/home/maiko/code/npm/backend-build-user-preferences/node_modules/serverless-dynamodb-local/index.js:164:21)
From previous event:
    at PluginManager.invoke (/home/maiko/.nvm/versions/node/v8.2.1/lib/node_modules/serverless/lib/classes/PluginManager.js:217:22)
    at PluginManager.run (/home/maiko/.nvm/versions/node/v8.2.1/lib/node_modules/serverless/lib/classes/PluginManager.js:236:17)
    at variables.populateService.then (/home/maiko/.nvm/versions/node/v8.2.1/lib/node_modules/serverless/lib/Serverless.js:107:33)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Serverless.run (/home/maiko/.nvm/versions/node/v8.2.1/lib/node_modules/serverless/lib/Serverless.js:94:74)
    at serverless.init.then (/home/maiko/.nvm/versions/node/v8.2.1/lib/node_modules/serverless/bin/serverless:32:50)
    at <anonymous>
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.2.1
     Serverless Version:     1.17.0
```

I commented in the PR on the spot where the code changes introduce this error.

**Comment by ChristopheBougere** [comment]
oops, sorry about that...
@maikokuppe could you have a look at https://github.com/99xt/serverless-dynamodb-local/pull/117 ?

**Comment by maikokuppe** [comment]
@ChristopheBougere Took me a while to figure out how to test this locally until I found that `npm i RedbirdHQ/serverless-dynamodb-local#bugfix/undefined-options` is enough :D

Thanks, that change works!
