### ISSUE TITLE
Reference Error: options is not defined

### ISSUE THREAD

**Issue by pablobarria** [99xt/serverless-dynamodb-local#119]
Greetings,

I have been working on a serverless project, for AWS Lambda, which uses DynamoDB, and using DynamoDB local / Serverless Offline for a dev environment.

For some reason it broke today, after I reinstalled the node_modules folder. I've been trying to determine what the problem is to no effect. Please understand that I'm relatively new to Serverless in general and I did not do the original setting up of the project.

The issue is with starting dynamodb-local. I can run sls dynamodb install with no issues, but then I get this error when running serverless offline start:
```
Reference Error ----------------------------------------

     options is not defined
```
I wound up creating a new serverless project from scratch, using the aws-nodejs template, and adding serverless-dynamodb-local as the only plugin. I'm still not able to start dynamodb, and I'm wondering if I missed a configuration step. I also tried downgrading to an older serverless version but the problem persists. 

I'm using Node 6.10.3 installed via Node Version Manager, on OSX. I tried with versions 1.9.0, 1.3.2 and 1.0.0

```
Dynamodb Local Started, Visit: http://localhost:8000/shell

  Reference Error ----------------------------------------

     options is not defined

     For debugging logs, run again after setting SLS_DEBUG env var.

  Stack Trace --------------------------------------------

ReferenceError: options is not defined
    at BbPromise.resolve.then (/Users/differentsmoke/Projects/my-project/node_modules/serverless-dynamodb-local/index.js:164:21)
    at tryCatcher (/Users/differentsmoke/Projects/my-project/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/differentsmoke/Projects/my-project/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/differentsmoke/Projects/my-project/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/differentsmoke/Projects/my-project/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/differentsmoke/Projects/my-project/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/differentsmoke/Projects/my-project/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/differentsmoke/Projects/my-project/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Infomation -----------------------------
     OS:                 darwin
     Node Version:       6.10.3
     Serverless Version: 1.0.0
```

Apologies if this is not the appropriate channel for this kind of question.

**Comment by lakindu95** [comment]
Hi Pablobarria,

We have merged a PR, check whether it works now in your local machine? 
#116  check this issue for further reference

**Comment by pablobarria** [comment]
Thank you very much @lakindu95 .
