### ISSUE TITLE
ClassNotFoundException on start right after installation

### ISSUE THREAD

**Issue by edmandiesamonte** [99xt/serverless-dynamodb-local#173]
**Actual Behaviour**

Getting this error:
```
java.lang.NoClassDefFoundError: com/almworks/sqlite4java/SQLiteJob
        at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBRequestHandler.getDBAccess(LocalDynamoDBRequestHandler.java:198)
        at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBRequestHandler.getHandler(LocalDynamoDBRequestHandler.java:189)
    ...
```

**Expected Behaviour**

No Error

**Steps to reproduce it**

1. `yarn add serverless-dynamodb-local --dev`
2. `sls dynamodb install`
3. `sls dynamodb start --migrate`

**LogCat for the issue**

Top Log:
```
Dynamodb Local Started, Visit: http://localhost:8000/shell
2018-06-30 20:03:38.346:WARN:oejs.AbstractHttpConnection:/
java.lang.NoClassDefFoundError: com/almworks/sqlite4java/SQLiteJob
        at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBRequestHandler.getDBAccess(LocalDynamoDBRequestHandler.java:198)
        at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBRequestHandler.getHandler(LocalDynamoDBRequestHandler.java:189)
```

Any reason for this issue? I already tried to `remove` then `install` again but with no luck.

Also, is there a support for running migrate on an existing DynamoDB Local? I used [this](https://github.com/instructure/dynamo-local-admin-docker) before.

**Comment by rishispeets** [comment]
I got the same error after upgrading from `0.2.30` to `0.2.36`. Reverting to the older version fixed it.

**Comment by mymail4blogs** [comment]
Thanks  this helped
