### ISSUE TITLE
"ValidationException: Too many items requested for the BatchWriteItem call" for 52 items in 3 batches 25 per batch

### ISSUE THREAD

**Issue by grzegorz-jakubiak** [99xt/serverless-dynamodb-local#175]
**Actual Behaviour**

ValidationException: Too many items requested for the BatchWriteItem call

**Expected Behaviour**

Add 52 items to DB as it happens on AWS.

**Steps to reproduce it**

The code I execute:

```
bulkCreate.params().forEach(param => {
  promises.push(dynamoDBClient.batchWrite(param).promise())
})

return Promise.all(promises).then(values => {
  return bulkCreate.serializableObject()
})
```

and BulkCreate class functions:

```
params () {
    return this.divideIntoBatches(this.preparedItems).map(itemsBatch => {
      return {
        RequestItems: {
          [this.tableName]: itemsBatch.map(batchItem => {
            return {
              PutRequest: {
                Item: batchItem
              }
            }
          })
        }
      }
    })
  }

  divideIntoBatches (arr, batchSize = 25) {
    let batches = []

    for (let i = 0; i < arr.length; i += batchSize) {
      batches.push(arr.slice(i, i + batchSize))
    }

    return batches
  }
```

**LogCat for the issue**

```
{ ValidationException: Too many items requested for the BatchWriteItem call
    at Request.extractError (/Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/Users/grzegorz/Documents/bima-subscription-service/node_modules/aws-sdk/lib/event_listeners.js:294:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  message: 'Too many items requested for the BatchWriteItem call',
  code: 'ValidationException',
  time: 2018-07-17T13:14:14.938Z,
  requestId: '3dbe5118-bb32-474a-8853-d4ca532e1343',
  statusCode: 400,
  retryable: false,
  retryDelay: 3.6367875349181733 }
```

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Would you like to work on the issue?**

Please let us know if you can work on it or the issue should be assigned to someone else.

**Comment by grzegorz-jakubiak** [comment]
It was a mistake in test helper code.
