### ISSUE TITLE
Unable to start serverless-dynamodb-offline, throwing 'sqlite : unable to open database file' error

### ISSUE THREAD

**Issue by sandeepp-cuelogic** [99xt/serverless-dynamodb-local#185]
**Actual Behaviour**
On starting dynamodb locally, it shows following error:     
```
Dynamodb Local Started, Visit: http://localhost:8000/shell
Sep 26, 2018 6:35:00 PM com.almworks.sqlite4java.Internal log
WARNING: [sqlite] cannot open DB[2]: com.almworks.sqlite4java.SQLiteException: [14] unable to open database file
Sep 26, 2018 6:31:05 PM com.almworks.sqlite4java.Internal log
SEVERE: [sqlite] SQLiteQueue[shared-local-instance.db]: error running job queue
com.almworks.sqlite4java.SQLiteException: [14] unable to open database file
	at com.almworks.sqlite4java.SQLiteConnection.open0(SQLiteConnection.java:1480)
	at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:282)
	at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:293)
	at com.almworks.sqlite4java.SQLiteQueue.openConnection(SQLiteQueue.java:464)
	at com.almworks.sqlite4java.SQLiteQueue.queueFunction(SQLiteQueue.java:641)
	at com.almworks.sqlite4java.SQLiteQueue.runQueue(SQLiteQueue.java:623)
	at com.almworks.sqlite4java.SQLiteQueue.access$000(SQLiteQueue.java:77)
	at com.almworks.sqlite4java.SQLiteQueue$1.run(SQLiteQueue.java:205)
	at java.base/java.lang.Thread.run(Thread.java:844)
```
After the above messages, `serverless offline start` fails
I am using VS Code editor and running launch configuration to run serverless.

State here what the feature should enable the user to do.

**Steps to reproduce it**

Concerned packages in package.json:      
```
    "serverless": "^1.32.0",
    "serverless-appsync-plugin": "1.0.1",
    "serverless-dynamodb-local": "^0.2.35",
    "serverless-step-functions": "^1.3.0",
```

**LogCat for the issue**

```
Dynamodb Local Started, Visit: http://localhost:8000/shell
Sep 26, 2018 6:35:00 PM com.almworks.sqlite4java.Internal log
WARNING: [sqlite] cannot open DB[2]: com.almworks.sqlite4java.SQLiteException: [14] unable to open database file
Sep 26, 2018 6:31:05 PM com.almworks.sqlite4java.Internal log
SEVERE: [sqlite] SQLiteQueue[shared-local-instance.db]: error running job queue
com.almworks.sqlite4java.SQLiteException: [14] unable to open database file
	at com.almworks.sqlite4java.SQLiteConnection.open0(SQLiteConnection.java:1480)
	at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:282)
	at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:293)
	at com.almworks.sqlite4java.SQLiteQueue.openConnection(SQLiteQueue.java:464)
	at com.almworks.sqlite4java.SQLiteQueue.queueFunction(SQLiteQueue.java:641)
	at com.almworks.sqlite4java.SQLiteQueue.runQueue(SQLiteQueue.java:623)
	at com.almworks.sqlite4java.SQLiteQueue.access$000(SQLiteQueue.java:77)
	at com.almworks.sqlite4java.SQLiteQueue$1.run(SQLiteQueue.java:205)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

![sqlite](https://user-images.githubusercontent.com/7858919/46082496-db2d6d80-c1bc-11e8-825a-1052eb822e07.png)

**Comment by kohakade** [comment]
- use database file by specifying --dbPath options.
- The dbPath is provided as relative then it required to set  serverless config servicePath.
- Instead if use absolute path then it works. 
  - if dbPath = "./" then the shared-local-instance.db file will be created at the root of the serverless.

**Comment by sandeepp-cuelogic** [comment]
Will try, thanks for responding.

**Comment by rehrumesh** [comment]
I hope the answer of @kohakade works. Closing the issue.

**Comment by mymail4blogs** [comment]
there is an issue in the latest build, I reverted to 0.2.30  
https://github.com/99xt/serverless-dynamodb-local/issues/173

**Comment by ncaucorp** [comment]
WARNING: [sqlite] SQLiteQueue[shared-local-instance.db]: stopped abnormally, reincarnating in 3000ms facing this issue

**Comment by mymail4blogs** [comment]
It looks like a folder permission issue while i was debugging with my teammate. When the dbpath was set to c:/Users/dynamodb, it resulted in the same error. However, altering it to c:/dynamodb resolved the issue. Within "C:/Users/", specific folders might have limited access permissions, as this directory usually holds user-specific data and settings.??
