### ISSUE TITLE
NPM version is outdated

### ISSUE THREAD

**Issue by raphaelmun** [99xt/serverless-dynamodb-local#61]
A new NPM version needs to be released. The version installed via NPM doesn't include the dummy-credentials and offline support, which results in an error like this when trying to run:

```
sls dynamodb executeAll
{ TimeoutError: Missing credentials in config
    at ClientRequest.<anonymous> (/Users/invisibletotoro/Documents/Development/GitHub/StashCloud/Stash/node_modules/aws-sdk/lib/http/node.js:56:34)
    at ClientRequest.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at Socket.emitTimeout (_http_client.js:620:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
  message: 'Missing credentials in config',
  code: 'CredentialsError',
  time: 2017-01-18T04:05:18.168Z,
  retryable: true,
  originalError: 
   { message: 'Could not load credentials from any providers',
     code: 'CredentialsError',
     time: 2017-01-18T04:05:18.168Z,
     retryable: true,
     originalError: 
      { message: 'Connection timed out after 1000ms',
        code: 'TimeoutError',
        time: 2017-01-18T04:05:18.166Z,
        retryable: true } } }
```

**Comment by AshanFernando** [comment]
@raphaelmun New NPM is released Version 0.2.16

**Comment by raphaelmun** [comment]
Thank you!

**Comment by pinalbhatt** [comment]
i am still getting above error with  "serverless-dynamodb-local": "^0.2.21",

**Comment by nenti** [comment]
There is an open pullrequest to allow operation without credentials. But for a quick fix you can just add your AWS credentials to your development system and get started.
https://serverless.com/framework/docs/providers/aws/guide/credentials/

**Comment by vitorreis** [comment]
I had the same problem today, I develop with using profiles and I didn't have a default one.
Adding a dummy default profile solved it for me.
```bash
$ aws configure
AWS Access Key ID [None]: 123
AWS Secret Access Key [None]: dummy
Default region name [None]: eu-west-1
Default output format [None]:
```
