### ISSUE TITLE
Error Installing Dynamodb

### ISSUE THREAD

**Issue by dipernaa** [99xt/serverless-dynamodb-local#65]
I get the following errors when trying to install dynamodb on my local machine and my travis builds.

Local Machine:
```
Error: Error getting DynamoDb local latest tar.gz location: 200
    at ClientRequest.<anonymous> (/Users/tony/git/pathway-server/node_modules/dynamodb-localhost/dynamodb/installer.js:14:26)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
/Users/tony/git/pathway-server/node_modules/dynamodb-localhost/dynamodb/installer.js:43
                    throw Error("Error in downloading Dynamodb local " + err);
                    ^

Error: Error in downloading Dynamodb local Error: connect ECONNREFUSED 127.0.0.1:80
    at Error (native)
    at ClientRequest.<anonymous> (/Users/tony/git/pathway-server/node_modules/dynamodb-localhost/dynamodb/installer.js:43:27)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Travis-CI:
```
Error: Error in downloading Dynamodb local Error: connect ECONNREFUSED 127.0.0.1:80
    at Error (native)
    at ClientRequest.<anonymous> (/home/travis/build/ProlifiqSoftware/pathway-server/node_modules/serverless-dynamodb-local/node_modules/dynamodb-localhost/dynamodb/installer.js:43:27)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1255:8)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickDomainCallback (node.js:392:17)
```

**Comment by Si1kIfY** [comment]
Fixed in upstream dependency - https://github.com/99xt/dynamodb-localhost/issues/7

**Comment by dipernaa** [comment]
@Si1kIfY What do you mean by "Fixed in upstream dependency"?

**Comment by Si1kIfY** [comment]
@dipernaa I mean serverless-dynamodb-local uses dependency dynamodb-localhost to run and it was fixed in dynamodb-localhost, see the link I posted: 99xt/dynamodb-localhost#7

Cheers

**Comment by dipernaa** [comment]
Updated package version, works fine now. Closing
